# Generated by Django 2.0 on 2018-03-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180316_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterlinks',
            name='post_date',
            field=models.CharField(max_length=20),
        ),
    ]
